# Generated by Django 5.2.14 on 2026-05-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_co_executors_task_cost_project_task_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='actual_hours',
            field=models.FloatField(default=0, verbose_name='Фактические часы'),
        ),
        migrations.AddField(
            model_name='project',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', verbose_name='Прикреплённые документы'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#667eea', help_text='HEX цвет проекта, например #667eea', max_length=7, verbose_name='Цвет проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='RUB', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='project',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Оплаченная сумма'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('partial', 'Частично'), ('paid', 'Оплачен полностью')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_hours',
            field=models.FloatField(default=0, verbose_name='Плановые часы'),
        ),
        migrations.AddField(
            model_name='project',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10, verbose_name='Уровень риска'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=500, verbose_name='Теги (через запятую)'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='task',
            name='reopened_count',
            field=models.IntegerField(default=0, verbose_name='Количество переоткрытий'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Назначена задача'), ('status_changed', 'Изменён статус'), ('commented', 'Новый комментарий'), ('overdue', 'Просрочена'), ('budget_warning', 'Предупреждение о бюджете')], max_length=30),
        ),
    ]
