# Generated by Django 5.2.14 on 2026-05-27 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_options_project_actual_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spent',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='task',
            name='cost',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Назначена задача'), ('status_changed', 'Изменён статус'), ('commented', 'Комментарий'), ('overdue', 'Просрочена')], max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#667eea', max_length=7),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='co_executors',
            field=models.ManyToManyField(blank=True, related_name='co_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reopened_count',
            field=models.IntegerField(default=0),
        ),
    ]
