# Generated by Django 5.2.14 on 2026-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_project_budget_project_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assigned', 'Назначена задача'), ('status_changed', 'Изменён статус'), ('commented', 'Комментарий'), ('overdue', 'Просрочена'), ('budget_warning', 'Предупреждение о бюджете'), ('project_assigned', 'Назначен менеджером проекта'), ('project_created', 'Создан новый проект')], max_length=30),
        ),
    ]
